# Real ARCTIC Training Configuration for HaWoR
# Updated config for actual model training

# Training Configuration
training:
  max_epochs: 10  # More epochs for real training
  batch_size: 1   # Keep small for memory efficiency
  learning_rate: 5.0e-05
  weight_decay: 1.0e-04
  min_lr: 1.0e-07
  grad_clip_val: 1.0
  warmup_epochs: 2
  early_stopping_patience: 5
  accumulate_grad_batches: 1

# ARCTIC specific parameters
arctic:
  data_root: thirdparty/arctic
  train_subjects: ["s01"]
  val_subjects: ["s01"]
  sequence_length: 8  # Shorter for memory efficiency
  max_sequences: 3
  images_per_camera: 50  # More images for real training
  use_multiple_cameras: false  # Egocentric only

# Model Configuration
model:
  img_size: 256
  patch_size: 16
  backbone_type: vit_small
  pretrained: false  # Start from scratch
  num_joints: 21

# Loss Weights
loss_weights:
  keypoint: 10.0
  mano_pose: 1.0
  mano_shape: 0.1
  temporal: 5.0
  camera: 1.0
  reprojection: 100.0
  consistency: 2.0

# Hardware Configuration
hardware:
  devices: 1
  accelerator: auto  # Let PyTorch Lightning choose
  precision: 32  # Use full precision for Mac stability
  find_unused_parameters: false

# Output Configuration
output_dir: outputs/arctic_training
log_dir: outputs/arctic_training/logs
checkpoint_dir: outputs/arctic_training/checkpoints
report_dir: outputs/arctic_training/reports

# Logging Configuration
logging:
  use_tensorboard: true
  use_wandb: false  # Disable for Mac testing
  tensorboard_log_dir: outputs/arctic_training/logs
  log_every_n_steps: 10  # More frequent for Mac
  log_images_every_n_steps: 50

# Additional parameters
experiment_name: hawor_arctic_mac_test
create_body_pose: false
render_log: true
log_steps: 50
