# Enhanced Training Configuration for HaWoR

data:
  training_data_dir: ./training_data
  validation_data_dir: ./training_data
  image_size: 256
  mano_data_dir: _DATA/data/
  mano_model_path: _DATA/data/mano
  num_workers: 0

model:
  backbone_type: vit
  pretrained_weights: null
  torch_compile: 0
  mano_gender: neutral
  num_hand_joints: 15
  st_module: false
  st_hdim: 512
  st_nlayer: 6
  motion_module: false
  motion_hdim: 384
  motion_nlayer: 6

training:
  max_epochs: 1
  batch_size: 2
  learning_rate: 1.0e-04
  weight_decay: 0.0001
  min_lr: 1.0e-07
  grad_clip_val: 1.0
  warmup_epochs: 5
  early_stopping_patience: 10
  accumulate_grad_batches: 1

loss:
  use_enhanced_loss: true
  use_adaptive_weights: true
  temporal_window: 5
  weights:
    KEYPOINTS_3D: 0.1
    KEYPOINTS_2D: 0.05
    GLOBAL_ORIENT: 0.01
    HAND_POSE: 0.01
    BETAS: 0.005
    MESH_VERTICES: 0.02
    MESH_FACES: 0.01
    TEMPORAL_CONSISTENCY: 0.005
    OCCLUSION_ROBUSTNESS: 0.01

evaluation:
  eval_every_n_epochs: 1
  val_check_interval: 1.0
  eval_metrics:
    - mpjpe_3d
    - mpjpe_2d
    - pck_3d_15mm
    - pck_2d_10px
    - temporal_consistency
    - mesh_quality

logging:
  use_tensorboard: true
  use_wandb: false
  tensorboard_log_dir: logs/tensorboard
  log_every_n_steps: 50
  log_images_every_n_steps: 500
  render_frequency: 1000

hardware:
  devices: 1
  accelerator: auto
  precision: 32
  find_unused_parameters: false

output:
  output_dir: ./training_output
  log_dir: ./training_logs
  checkpoint_dir: checkpoints
  report_dir: reports
  save_top_k: 3
  save_every_n_epochs: 10
  monitor: val/loss
  mode: min

# Additional parameters
mano_mean_params: _DATA/data/mano_mean_params.npz
create_body_pose: false
render_log: true
log_steps: 1000
wandb_project: hawor-training
experiment_name: hawor_experiment
